//
// Camera.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Camera: Codable { 


    public var id: Int
    public var createdAt: String
    public var updatedAt: String
    public var name: String
    public var serial: String
    public var fwVersion: String
    public var type: String
    public var enabled: Bool
    public var thumbnail: String
    public var status: String
    public var battery: String
    public var usageRate: Bool
    public var networkId: Int
    public var signals: CameraSignals
    public var localStorageEnabled: Bool
    public var localStorageCompatible: Bool

    public init(id: Int, createdAt: String, updatedAt: String, name: String, serial: String, fwVersion: String, type: String, enabled: Bool, thumbnail: String, status: String, battery: String, usageRate: Bool, networkId: Int, signals: CameraSignals, localStorageEnabled: Bool, localStorageCompatible: Bool) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.name = name
        self.serial = serial
        self.fwVersion = fwVersion
        self.type = type
        self.enabled = enabled
        self.thumbnail = thumbnail
        self.status = status
        self.battery = battery
        self.usageRate = usageRate
        self.networkId = networkId
        self.signals = signals
        self.localStorageEnabled = localStorageEnabled
        self.localStorageCompatible = localStorageCompatible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case name
        case serial
        case fwVersion = "fw_version"
        case type
        case enabled
        case thumbnail
        case status
        case battery
        case usageRate = "usage_rate"
        case networkId = "network_id"
        case signals
        case localStorageEnabled = "local_storage_enabled"
        case localStorageCompatible = "local_storage_compatible"
    }

}
