//
// CameraSignals.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CameraSignals: Codable { 


    public var lfr: Int
    public var wifi: Int
    public var temp: Int
    public var battery: Int

    public init(lfr: Int, wifi: Int, temp: Int, battery: Int) {
        self.lfr = lfr
        self.wifi = wifi
        self.temp = temp
        self.battery = battery
    }

}
