//
// HomeScreenResponseAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeScreenResponseAccount: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var emailVerified: Bool
    public var emailVerificationRequired: Bool

    public init(id: Int, emailVerified: Bool, emailVerificationRequired: Bool) {
        self.id = id
        self.emailVerified = emailVerified
        self.emailVerificationRequired = emailVerificationRequired
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case emailVerified = "email_verified"
        case emailVerificationRequired = "email_verification_required"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(emailVerified, forKey: .emailVerified)
        try container.encode(emailVerificationRequired, forKey: .emailVerificationRequired)
    }
}

