//
// HomeScreenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HomeScreenResponse: Codable { 


    public var account: HomeScreenResponseAccount
    public var cameras: [Camera]

    public init(account: HomeScreenResponseAccount, cameras: [Camera]) {
        self.account = account
        self.cameras = cameras
    }

}
