//
// InitialCommandResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InitialCommandResponse: Codable {

    public var id: Int

    public init(id: Int) {
        self.id = id
    }

}
