//
// Issue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Issue: Codable, Hashable {

    public var unknown: Int?

    public init(unknown: Int? = nil) {
        self.unknown = unknown
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unknown = "__unknown"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(unknown, forKey: .unknown)
    }
}

