//
// Issue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Issue: Codable { 


    public var unknown: Int?

    public init(unknown: Int?) {
        self.unknown = unknown
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case unknown = "__unknown"
    }

}
