//
// LoginResponseAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LoginResponseAccount: Codable { 


    public var id: Int
    public var verificationRequired: Bool
    public var newAccount: Bool

    public init(id: Int, verificationRequired: Bool, newAccount: Bool) {
        self.id = id
        self.verificationRequired = verificationRequired
        self.newAccount = newAccount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case verificationRequired = "verification_required"
        case newAccount = "new_account"
    }

}
