//
// LoginResponseAuthtoken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponseAuthtoken: Codable {

    public var authtoken: String
    public var message: String

    public init(authtoken: String, message: String) {
        self.authtoken = authtoken
        self.message = message
    }

}
