//
// LoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponse: Codable {

    public var account: LoginResponseAccount
    public var client: LoginResponseClient
    public var authtoken: LoginResponseAuthtoken
    public var region: LoginResponseRegion
    public var lockoutTimeRemaining: Int
    public var forcePasswordReset: Bool
    public var allowPinResendSeconds: Int

    public init(account: LoginResponseAccount, client: LoginResponseClient, authtoken: LoginResponseAuthtoken, region: LoginResponseRegion, lockoutTimeRemaining: Int, forcePasswordReset: Bool, allowPinResendSeconds: Int) {
        self.account = account
        self.client = client
        self.authtoken = authtoken
        self.region = region
        self.lockoutTimeRemaining = lockoutTimeRemaining
        self.forcePasswordReset = forcePasswordReset
        self.allowPinResendSeconds = allowPinResendSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case client
        case authtoken
        case region
        case lockoutTimeRemaining = "lockout_time_remaining"
        case forcePasswordReset = "force_password_reset"
        case allowPinResendSeconds = "allow_pin_resend_seconds"
    }

}
