//
// LoginResponseVerificationPhone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginResponseVerificationPhone: Codable, JSONEncodable, Hashable {

    public var _required: Bool
    public var channel: String

    public init(_required: Bool, channel: String) {
        self._required = _required
        self.channel = channel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _required = "required"
        case channel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_required, forKey: ._required)
        try container.encode(channel, forKey: .channel)
    }
}

