//
// LoginResponsePhone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponsePhone: Codable {

    public var number: String
    public var last4Digits: String
    public var countryCallingCode: String
    public var valid: Bool

    public init(number: String, last4Digits: String, countryCallingCode: String, valid: Bool) {
        self.number = number
        self.last4Digits = last4Digits
        self.countryCallingCode = countryCallingCode
        self.valid = valid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case last4Digits = "last_4_digits"
        case countryCallingCode = "country_calling_code"
        case valid
    }

}
