//
// LoginResponseVerificationEmail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponseVerificationEmail: Codable {

    public var _required: Bool

    public init(_required: Bool) {
        self._required = _required
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _required = "required"
    }

}
