//
// LoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponse: Codable {

    public var account: LoginResponseAccount
    public var auth: LoginResponseAuth
    public var phone: LoginResponsePhone
    public var verification: LoginResponseVerification
    public var lockoutTimeRemaining: Int
    public var forcePasswordReset: Bool
    public var allowPinResendSeconds: Int

    public init(account: LoginResponseAccount, auth: LoginResponseAuth, phone: LoginResponsePhone, verification: LoginResponseVerification, lockoutTimeRemaining: Int, forcePasswordReset: Bool, allowPinResendSeconds: Int) {
        self.account = account
        self.auth = auth
        self.phone = phone
        self.verification = verification
        self.lockoutTimeRemaining = lockoutTimeRemaining
        self.forcePasswordReset = forcePasswordReset
        self.allowPinResendSeconds = allowPinResendSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case auth
        case phone
        case verification
        case lockoutTimeRemaining = "lockout_time_remaining"
        case forcePasswordReset = "force_password_reset"
        case allowPinResendSeconds = "allow_pin_resend_seconds"
    }

}
