//
// LoginResponseRegion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LoginResponseRegion: Codable { 


    public var tier: String
    public var description: String
    public var code: String

    public init(tier: String, description: String, code: String) {
        self.tier = tier
        self.description = description
        self.code = code
    }

}
