//
// LoginResponseVerification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoginResponseVerification: Codable {

    public var email: LoginResponseVerificationEmail
    public var phone: LoginResponseVerificationPhone

    public init(email: LoginResponseVerificationEmail, phone: LoginResponseVerificationPhone) {
        self.email = email
        self.phone = phone
    }

}
