//
// Media.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Media: Codable {

    public enum Device: String, Codable, CaseIterable {
        case camera = "camera"
    }
    public enum ModelType: String, Codable, CaseIterable {
        case video = "video"
    }
    public enum Source: String, Codable, CaseIterable {
        case liveview = "liveview"
        case pir = "pir"
    }
    public var id: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var deleted: Bool
    public var device: Device
    public var deviceId: Int
    public var deviceName: String
    public var networkId: Int
    public var networkName: String
    public var type: ModelType
    public var source: Source
    public var watched: Bool
    public var partial: Bool?
    public var thumbnail: String
    public var media: String
    public var timeZone: String

    public init(id: Int, createdAt: Date, updatedAt: Date, deleted: Bool, device: Device, deviceId: Int, deviceName: String, networkId: Int, networkName: String, type: ModelType, source: Source, watched: Bool, partial: Bool?, thumbnail: String, media: String, timeZone: String) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.deleted = deleted
        self.device = device
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.networkId = networkId
        self.networkName = networkName
        self.type = type
        self.source = source
        self.watched = watched
        self.partial = partial
        self.thumbnail = thumbnail
        self.media = media
        self.timeZone = timeZone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case deleted
        case device
        case deviceId = "device_id"
        case deviceName = "device_name"
        case networkId = "network_id"
        case networkName = "network_name"
        case type
        case source
        case watched
        case partial
        case thumbnail
        case media
        case timeZone = "time_zone"
    }

}
