//
// Network.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Network: Codable { 


    public var id: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var name: String
    public var timeZone: String
    public var dst: Bool
    public var armed: Bool
    public var lvSave: Bool

    public init(id: Int, createdAt: Date, updatedAt: Date, name: String, timeZone: String, dst: Bool, armed: Bool, lvSave: Bool) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.name = name
        self.timeZone = timeZone
        self.dst = dst
        self.armed = armed
        self.lvSave = lvSave
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case name
        case timeZone = "time_zone"
        case dst
        case armed
        case lvSave = "lv_save"
    }

}
