//
// Network.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Network: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var name: String
    public var timeZone: String
    public var dst: Bool
    public var armed: Bool
    public var lvSave: Bool

    public init(id: Int, createdAt: Date, updatedAt: Date, name: String, timeZone: String, dst: Bool, armed: Bool, lvSave: Bool) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.name = name
        self.timeZone = timeZone
        self.dst = dst
        self.armed = armed
        self.lvSave = lvSave
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case name
        case timeZone = "time_zone"
        case dst
        case armed
        case lvSave = "lv_save"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(name, forKey: .name)
        try container.encode(timeZone, forKey: .timeZone)
        try container.encode(dst, forKey: .dst)
        try container.encode(armed, forKey: .armed)
        try container.encode(lvSave, forKey: .lvSave)
    }
}

