//
// UnexpectedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UnexpectedResponse: Codable { 


    public var message: String
    public var code: Int

    public init(message: String, code: Int) {
        self.message = message
        self.code = code
    }

}
