//
// VerifyPinResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VerifyPinResponse: Codable { 


    public var valid: Bool
    public var requireNewPin: Bool
    public var message: String
    public var code: Int

    public init(valid: Bool, requireNewPin: Bool, message: String, code: Int) {
        self.valid = valid
        self.requireNewPin = requireNewPin
        self.message = message
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case valid
        case requireNewPin = "require_new_pin"
        case message
        case code
    }

}
