//
// VerifyPinRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyPinRequest: Codable, JSONEncodable, Hashable {

    public var pin: String

    public init(pin: String) {
        self.pin = pin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pin, forKey: .pin)
    }
}

