//
// VerifyPinResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyPinResponse: Codable, JSONEncodable, Hashable {

    public var valid: Bool
    public var requireNewPin: Bool
    public var message: String
    public var code: Int

    public init(valid: Bool, requireNewPin: Bool, message: String, code: Int) {
        self.valid = valid
        self.requireNewPin = requireNewPin
        self.message = message
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case valid
        case requireNewPin = "require_new_pin"
        case message
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(valid, forKey: .valid)
        try container.encode(requireNewPin, forKey: .requireNewPin)
        try container.encode(message, forKey: .message)
        try container.encode(code, forKey: .code)
    }
}

