//
// VerifyPinRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VerifyPinRequest: Codable { 


    public var pin: String

    public init(pin: String) {
        self.pin = pin
    }

}
