//
// BlinkDefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BlinkDefaultAPI {

    /**

     - parameter networkID: (path)  
     - parameter cameraID: (path)  
     - returns: InitialCommandResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func disableCamera(networkID: Int, cameraID: Int) async throws -> InitialCommandResponse {
        let requestBuilder = disableCameraWithRequestBuilder(networkID: networkID, cameraID: cameraID)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - POST /network/{networkID}/camera/{cameraID}/disable
     - parameter networkID: (path)  
     - parameter cameraID: (path)  
     - returns: RequestBuilder<InitialCommandResponse> 
     */
    open class func disableCameraWithRequestBuilder(networkID: Int, cameraID: Int) -> RequestBuilder<InitialCommandResponse> {
        var localVariablePath = "/network/{networkID}/camera/{cameraID}/disable"
        let networkIDPreEscape = "\(APIHelper.mapValueToPathItem(networkID))"
        let networkIDPostEscape = networkIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{networkID}", with: networkIDPostEscape, options: .literal, range: nil)
        let cameraIDPreEscape = "\(APIHelper.mapValueToPathItem(cameraID))"
        let cameraIDPostEscape = cameraIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{cameraID}", with: cameraIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InitialCommandResponse>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter networkID: (path)  
     - parameter cameraID: (path)  
     - returns: InitialCommandResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func enableCamera(networkID: Int, cameraID: Int) async throws -> InitialCommandResponse {
        let requestBuilder = enableCameraWithRequestBuilder(networkID: networkID, cameraID: cameraID)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - POST /network/{networkID}/camera/{cameraID}/enable
     - parameter networkID: (path)  
     - parameter cameraID: (path)  
     - returns: RequestBuilder<InitialCommandResponse> 
     */
    open class func enableCameraWithRequestBuilder(networkID: Int, cameraID: Int) -> RequestBuilder<InitialCommandResponse> {
        var localVariablePath = "/network/{networkID}/camera/{cameraID}/enable"
        let networkIDPreEscape = "\(APIHelper.mapValueToPathItem(networkID))"
        let networkIDPostEscape = networkIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{networkID}", with: networkIDPostEscape, options: .literal, range: nil)
        let cameraIDPreEscape = "\(APIHelper.mapValueToPathItem(cameraID))"
        let cameraIDPostEscape = cameraIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{cameraID}", with: cameraIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InitialCommandResponse>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter media: (path) Media URL 
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getThumbnail(media: String) async throws -> URL {
        let requestBuilder = getThumbnailWithRequestBuilder(media: media)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - GET /{media}.jpg
     - parameter media: (path) Media URL 
     - returns: RequestBuilder<URL> 
     */
    open class func getThumbnailWithRequestBuilder(media: String) -> RequestBuilder<URL> {
        var localVariablePath = "/{media}.jpg"
        let mediaPreEscape = "\(APIHelper.mapValueToPathItem(media))"
        let mediaPostEscape = mediaPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{media}", with: mediaPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter media: (path) Media URL 
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVideo(media: String) async throws -> URL {
        let requestBuilder = getVideoWithRequestBuilder(media: media)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - GET /{media}
     - parameter media: (path) Media URL 
     - returns: RequestBuilder<URL> 
     */
    open class func getVideoWithRequestBuilder(media: String) -> RequestBuilder<URL> {
        var localVariablePath = "/{media}"
        let mediaPreEscape = "\(APIHelper.mapValueToPathItem(media))"
        let mediaPostEscape = mediaPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{media}", with: mediaPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter accountID: (path) Account ID 
     - parameter since: (query)  
     - parameter page: (query) Page number for multiple pages of results 
     - returns: VideoEvents
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVideoEvents(accountID: Int, since: Date, page: Int) async throws -> VideoEvents {
        let requestBuilder = getVideoEventsWithRequestBuilder(accountID: accountID, since: since, page: page)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - GET /api/v1/accounts/{accountID}/media/changed
     - parameter accountID: (path) Account ID 
     - parameter since: (query)  
     - parameter page: (query) Page number for multiple pages of results 
     - returns: RequestBuilder<VideoEvents> 
     */
    open class func getVideoEventsWithRequestBuilder(accountID: Int, since: Date, page: Int) -> RequestBuilder<VideoEvents> {
        var localVariablePath = "/api/v1/accounts/{accountID}/media/changed"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "since": (wrappedValue: since.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VideoEvents>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter accountID: (path) Account ID 
     - returns: HomeScreenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func homescreen(accountID: Int) async throws -> HomeScreenResponse {
        let requestBuilder = homescreenWithRequestBuilder(accountID: accountID)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - GET /api/v3/accounts/{accountID}/homescreen
     - parameter accountID: (path) Account ID 
     - returns: RequestBuilder<HomeScreenResponse> 
     */
    open class func homescreenWithRequestBuilder(accountID: Int) -> RequestBuilder<HomeScreenResponse> {
        var localVariablePath = "/api/v3/accounts/{accountID}/homescreen"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HomeScreenResponse>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter loginRequest: (body)  
     - returns: LoginResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func login(loginRequest: LoginRequest) async throws -> LoginResponse {
        let requestBuilder = loginWithRequestBuilder(loginRequest: loginRequest)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - POST /api/v5/account/login
     - parameter loginRequest: (body)  
     - returns: RequestBuilder<LoginResponse> 
     */
    open class func loginWithRequestBuilder(loginRequest: LoginRequest) -> RequestBuilder<LoginResponse> {
        let localVariablePath = "/api/v5/account/login"
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LoginResponse>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter accountID: (path) Account ID 
     - parameter clientID: (path) Client ID 
     - parameter verifyPinRequest: (body)  
     - returns: VerifyPinResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func verifyPin(accountID: Int, clientID: Int, verifyPinRequest: VerifyPinRequest) async throws -> VerifyPinResponse {
        let requestBuilder = verifyPinWithRequestBuilder(accountID: accountID, clientID: clientID, verifyPinRequest: verifyPinRequest)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - POST /api/v4/account/{accountID}/client/{clientID}/pin/verify
     - parameter accountID: (path) Account ID 
     - parameter clientID: (path) Client ID 
     - parameter verifyPinRequest: (body)  
     - returns: RequestBuilder<VerifyPinResponse> 
     */
    open class func verifyPinWithRequestBuilder(accountID: Int, clientID: Int, verifyPinRequest: VerifyPinRequest) -> RequestBuilder<VerifyPinResponse> {
        var localVariablePath = "/api/v4/account/{accountID}/client/{clientID}/pin/verify"
        let accountIDPreEscape = "\(APIHelper.mapValueToPathItem(accountID))"
        let accountIDPostEscape = accountIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{accountID}", with: accountIDPostEscape, options: .literal, range: nil)
        let clientIDPreEscape = "\(APIHelper.mapValueToPathItem(clientID))"
        let clientIDPostEscape = clientIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{clientID}", with: clientIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = BlinkOpenAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyPinRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VerifyPinResponse>.Type = BlinkOpenAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
